spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/*
spring:
  application:
    name: microservice-product-config
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
